### ISSUE TITLE
github actionsのオプションが間違っている?

### ISSUE THREAD

**Issue by Quesys-tech** [VirtualAviationJapan/vss_signage#8]
[.github/workflows/publish.yml](https://github.com/VirtualAviationJapan/vss_signage/blob/d1f3556e627865e7a2c878880b7bcfe34e883b9a/.github/workflows/publish.yml)
のnode-versionとcacheのオプションが間違っているっぽい
```yaml       
      - uses: pnpm/action-setup@v4
        with:
          node-version: 22
          cache: pnpm
```
